{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "## What is NumPy?\n",
        "\n",
        "\u003Cul\u003E\u003Cli\u003ENumPy is a Python library used for working with arrays.\u003C/li\u003E\n",
        "\n",
        "\u003Cli\u003EIt has functions for working in domain of linear algebra, fourier transform, and matrices.\u003C/li\u003E\n",
        "\n",
        "\u003Cli\u003ENumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.\u003C/li\u003E\u003C/ul\u003E"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "## Why Use NumPy?\n",
        "\n",
        "\u003Cul\u003E\u003Cli\u003EIn Python we have lists that serve the purpose of arrays, but they are slow to process.\u003C/li\u003E\n",
        "\n",
        "\u003Cli\u003ENumPy aims to provide an array object that is up to 50x faster than traditional Python lists.\u003C/li\u003E\n",
        "\n",
        "\u003Cli\u003EThe array object in NumPy is called \u003Cb\u003Endarray\u003C/b\u003E, it provides a lot of supporting functions that make working with \u003Cb\u003Endarray\u003C/b\u003E very easy.\u003C/li\u003E\u003C/ul\u003E"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "## Import NumPy\n",
        "\n",
        "Once NumPy is installed, import it in your applications by adding the \u003Cb\u003Eimport\u003C/b\u003E keyword:"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {

      },
      "outputs": [],
      "source": [
        "import numpy"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "## NumPy as np\n",
        "\n",
        "\u003Cul\u003E\u003Cli\u003ENumPy is usually imported under the np alias.\u003C/li\u003E\n",
        "\u003Cli\u003ECreate an alias with the as keyword while importing:\u003C/li\u003E\u003C/ul\u003E"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {

      },
      "outputs": [],
      "source": [
        "import numpy as np"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "## Checking NumPy Version\n",
        "\n",
        "The version string is stored under __ __version__ __ attribute."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "1.26.4\n"
          ]
        }
      ],
      "source": [
        "print(np.__version__)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "## Create a NumPy ndarray Object\n",
        "\u003Cul\u003E\u003Cli\u003ENumPy is used to work with arrays.\u003C/li\u003E\n",
        "    \u003Cli\u003EThe array object in NumPy is called \u003Cb\u003Endarray\u003C/b\u003E.\u003C/li\u003E\n",
        "    \u003Cli\u003EWe can create a NumPy \u003Cb\u003Endarray\u003C/b\u003E object by using the \u003Cb\u003Earray()\u003C/b\u003E function.\u003C/li\u003E"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 5,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "[101 201 301 401 501]\n",
            "\u003Cclass 'numpy.ndarray'\u003E\n"
          ]
        }
      ],
      "source": [
        "arr = np.array([101, 201, 301,  401, 501])\n",
        "\n",
        "print(arr)\n",
        "\n",
        "print(type(arr))"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "To create an \u003Cb\u003Endarray\u003C/b\u003E, we can pass a list, tuple or any array-like object into the \u003Cb\u003Earray()\u003C/b\u003E method, and it will be converted into an \u003Cb\u003Endarray\u003C/b\u003E:"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 6,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "['Angel' 'Shemi' 'Marvel' 'Linda']\n",
            "[41 32 21 19]\n",
            "{'CSC102': 89, 'MTH 102': 77, 'CHM 102': 69, 'GST 102': 99}\n",
            "\u003Cclass 'numpy.ndarray'\u003E\n"
          ]
        }
      ],
      "source": [
        "nameList = ['Angel', \"Shemi\", \"Marvel\", \"Linda\"]\n",
        "\n",
        "ageTuple = (41, 32, 21, 19)\n",
        "\n",
        "gradeDict = {\"CSC102\": 89, \"MTH 102\": 77, \"CHM 102\": 69, \"GST 102\": 99}\n",
        "\n",
        "arr_nameList = np.array(nameList)\n",
        "\n",
        "arr_ageTuple = np.array(ageTuple)\n",
        "\n",
        "arr_gradeDict = np.array(gradeDict)\n",
        "\n",
        "print(arr_nameList)\n",
        "print(arr_ageTuple)\n",
        "print(arr_gradeDict)\n",
        "print(type(arr_gradeDict))"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "## Dimensions in Array\n",
        "A dimension in arrays is one level of array depth (nested arrays).\n",
        "Note: The shape of an array can be gotten through the \u003Cb\u003Eshape\u003C/b\u003E attribute"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "### 0-Dimension\n",
        "0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 9,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdin",
          "output_type": "stream",
          "text": [
            "How many students are in the CSC 102 class? 12\n"
          ]
        },
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "There are 12 students in CSC 102 class\n"
          ]
        }
      ],
      "source": [
        "classNum = int(input(\"How many students are in the CSC 102 class?\"))\n",
        "\n",
        "class_arr = np.array(classNum)\n",
        "\n",
        "if (class_arr == 1):\n",
        "    print(\"There is only \", class_arr, \"student in CSC 102 class\" )\n",
        "else:\n",
        "    print(\"There are\", class_arr, \"students in CSC 102 class\" )"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "### 1-D Arrays\n",
        "\u003Cul\u003E\u003Cli\u003EAn array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.\u003C/li\u003E\n",
        "    \u003Cli\u003EThese are the most common and basic arrays.\u003C/li\u003E\n",
        "\u003C/ul\u003E"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 16,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "[1 2 3 4 5]\n",
            "(5,)\n"
          ]
        }
      ],
      "source": [
        "arr = np.array([1, 2, 3, 4, 5])\n",
        "\n",
        "print(arr)\n",
        "print(arr.shape)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "### 2-D Arrays\n",
        "\u003Cul\u003E\u003Cli\u003EAn array that has 1-D arrays as its elements is called a 2-D array.\u003C/li\u003E\n",
        "    \u003Cli\u003EThese are often used to represent matrix or 2nd order tensors.\u003C/li\u003E\u003C/ul\u003E"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 7,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "[[1 2 3]\n",
            " [4 5 6]\n",
            " [7 9 8]]\n",
            "(3, 3)\n"
          ]
        }
      ],
      "source": [
        "arr = np.array([[1, 2, 3], [4, 5, 6], [7, 9, 8]])\n",
        "\n",
        "print(arr)\n",
        "print(arr.shape)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "### 3-D arrays\n",
        "\u003Cul\u003E\u003Cli\u003EAn array that has 2-D arrays (matrices) as its elements is called 3-D array.\u003C/li\u003E\n",
        "    \u003Cli\u003EThese are often used to represent a 3rd order tensor.\u003C/li\u003E\u003C/ul\u003E"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 19,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "[[[1 2 3]\n",
            "  [4 5 6]]\n",
            "\n",
            " [[1 2 3]\n",
            "  [4 5 6]]\n",
            "\n",
            " [[1 2 3]\n",
            "  [4 5 6]]]\n",
            "(3, 2, 3)\n"
          ]
        }
      ],
      "source": [
        "arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])\n",
        "\n",
        "print(arr)\n",
        "print(arr.shape)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "## Check Number of Dimensions?\n",
        "NumPy Arrays provides the \u003Cb\u003Endim\u003C/b\u003E attribute that returns an integer that tells us how many dimensions the array have"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 13,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "0\n",
            "3\n",
            "2\n",
            "1\n"
          ]
        }
      ],
      "source": [
        "a = np.array(42)\n",
        "b = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])\n",
        "c = np.array([[1, 2, 3], [4, 5, 6]])\n",
        "d = np.array([1, 2, 3, 4, 5])\n",
        "\n",
        "#print(b)\n",
        "\n",
        "print(a.ndim)\n",
        "print(b.ndim)\n",
        "print(c.ndim)\n",
        "print(d.ndim)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "## Higher Dimensional Arrays\n",
        "\u003Cul\u003E\u003Cli\u003EAn array can have any number of dimensions.\u003C/li\u003E\n",
        "    \u003Cli\u003EWhen the array is created, you can define the number of dimensions by using the ndmin argument.\u003C/li\u003E\n",
        "\u003Cli\u003EIn this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.\u003C/li\u003E\u003C/ul\u003E"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 15,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "[[[[[[[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]]]]]]]\n",
            "number of dimensions : 21\n"
          ]
        },
        {
          "data": {
            "text/plain": [
              "(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4)"
            ]
          },
          "execution_count": 15,
          "metadata": {

          },
          "output_type": "execute_result"
        }
      ],
      "source": [
        "arr = np.array([1, 2, 3, 4], ndmin=21)\n",
        "\n",
        "print(arr)\n",
        "print('number of dimensions :', arr.ndim)\n",
        "arr.shape"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "## Access Array Elements"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 20,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "2\n"
          ]
        }
      ],
      "source": [
        "arr = np.array([1, 2, 3, 4])\n",
        "\n",
        "print(arr[1])"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "## Access 2-D Arrays"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 22,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "the 5th element on 2nd row:  10\n"
          ]
        }
      ],
      "source": [
        "arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])\n",
        "\n",
        "\n",
        "print('the 5th element on 2nd row: ', arr[1, 4])"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "## Access 3-D Arrays"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 8,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "[[[ 1  2  3  4  5]\n",
            "  [ 4  5  6  0  6]]\n",
            "\n",
            " [[ 7  8  9  8  5]\n",
            "  [10 11 12  6  9]]]\n",
            "(2, 2, 5)\n",
            "4\n"
          ]
        }
      ],
      "source": [
        "arr = np.array([[[1, 2, 3, 4, 5], [4, 5, 6, 0, 6]], [[7, 8, 9, 8, 5], [10, 11, 12, 6, 9]]])\n",
        "\n",
        "print(arr)\n",
        "print(arr.shape)\n",
        "print(arr[0, 0, 3])"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "## Negative Indexing\n",
        "Use negative indexing to access an array from the end."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 26,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Last element from 1st dim:  5\n"
          ]
        }
      ],
      "source": [
        "arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])\n",
        "\n",
        "print('Last element from 1st dim: ', arr[0, -1])"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "## Slicing arrays\n",
        "\u003Cul\u003E\u003Cli\u003ESlicing in python means taking elements from one given index to another given index.\u003C/li\u003E\n",
        "    \u003Cli\u003EWe pass slice instead of index like this: \u003Cb\u003E[start:end]\u003C/b\u003E.\u003C/li\u003E\n",
        "    \u003Cli\u003EWe can also define the step, like this: \u003Cb\u003E[start:end:step]\u003C/b\u003E.\u003C/li\u003E\n",
        "    \u003Cli\u003EIf we don't pass start its considered 0\u003C/li\u003E\n",
        "    \u003Cli\u003EIf we don't pass end its considered length of array in that dimension\u003C/li\u003E\n",
        "    \u003Cli\u003EIf we don't pass step its considered 1\u003C/li\u003E\u003C/ul\u003E"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 27,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "[2 3 4 5]\n"
          ]
        }
      ],
      "source": [
        "# Slice elements from index 1 to index 5 from the following array:\n",
        "\n",
        "arr = np.array([1, 2, 3, 4, 5, 6, 7])\n",
        "\n",
        "print(arr[1:5])"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 28,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "[5 6 7]\n"
          ]
        }
      ],
      "source": [
        "# Slice elements from index 4 to the end of the array:\n",
        "\n",
        "arr = np.array([1, 2, 3, 4, 5, 6, 7])\n",
        "\n",
        "print(arr[4:])"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 29,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "[1 2 3 4]\n"
          ]
        }
      ],
      "source": [
        "# Slice elements from the beginning to index 4 (not included):\n",
        "\n",
        "arr = np.array([1, 2, 3, 4, 5, 6, 7])\n",
        "\n",
        "print(arr[:4])"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "## Iterating Arrays"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 30,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "1 [1 2 3]\n",
            "2 [1 2 3]\n",
            "3 [1 2 3]\n",
            "4 [4 5 6]\n",
            "5 [4 5 6]\n",
            "6 [4 5 6]\n"
          ]
        }
      ],
      "source": [
        "#Iterate on each scalar element of the 2-D array:\n",
        "\n",
        "arr = np.array([[1, 2, 3], [4, 5, 6]])\n",
        "\n",
        "for x in arr:\n",
        "    for y in x:\n",
        "        print(y,x)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 31,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "4\n",
            "2\n",
            "10\n",
            "8\n"
          ]
        }
      ],
      "source": [
        "# Iterate on the elements of the following 3-D array:\n",
        "\n",
        "arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])\n",
        "\n",
        "#print(arr)\n",
        "\n",
        "for x in arr:\n",
        "    print(x[1,0])\n",
        "    print(x[0,1])"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 32,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "1 [1 2 3] [[1 2 3]\n",
            " [4 5 6]]\n",
            "2 [1 2 3] [[1 2 3]\n",
            " [4 5 6]]\n",
            "3 [1 2 3] [[1 2 3]\n",
            " [4 5 6]]\n",
            "4 [4 5 6] [[1 2 3]\n",
            " [4 5 6]]\n",
            "5 [4 5 6] [[1 2 3]\n",
            " [4 5 6]]\n",
            "6 [4 5 6] [[1 2 3]\n",
            " [4 5 6]]\n",
            "7 [7 8 9] [[ 7  8  9]\n",
            " [10 11 12]]\n",
            "8 [7 8 9] [[ 7  8  9]\n",
            " [10 11 12]]\n",
            "9 [7 8 9] [[ 7  8  9]\n",
            " [10 11 12]]\n",
            "10 [10 11 12] [[ 7  8  9]\n",
            " [10 11 12]]\n",
            "11 [10 11 12] [[ 7  8  9]\n",
            " [10 11 12]]\n",
            "12 [10 11 12] [[ 7  8  9]\n",
            " [10 11 12]]\n"
          ]
        }
      ],
      "source": [
        "arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])\n",
        "\n",
        "for x in arr:\n",
        "    for y in x:\n",
        "        for z in y:\n",
        "            print(z,y,x)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "## Joining NumPy Arrays\n",
        "We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 33,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "[1 2 3 4 5 6]\n"
          ]
        }
      ],
      "source": [
        "# Join two arrays\n",
        "\n",
        "arr1 = np.array([1, 2, 3])\n",
        "\n",
        "arr2 = np.array([4, 5, 6])\n",
        "\n",
        "arr = np.concatenate((arr1, arr2))\n",
        "\n",
        "print(arr)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 10,
      "metadata": {
        "scrolled": true
      },
      "outputs": [
        {
          "data": {
            "text/plain": [
              "\u001B[1;31mSignature:\u001B[0m       \u001B[0mnp\u001B[0m\u001B[1;33m.\u001B[0m\u001B[0mappend\u001B[0m\u001B[1;33m(\u001B[0m\u001B[0marr\u001B[0m\u001B[1;33m,\u001B[0m \u001B[0mvalues\u001B[0m\u001B[1;33m,\u001B[0m \u001B[0maxis\u001B[0m\u001B[1;33m=\u001B[0m\u001B[1;32mNone\u001B[0m\u001B[1;33m)\u001B[0m\u001B[1;33m\u001B[0m\u001B[1;33m\u001B[0m\u001B[0m\n",
              "\u001B[1;31mCall signature:\u001B[0m  \u001B[0mnp\u001B[0m\u001B[1;33m.\u001B[0m\u001B[0mappend\u001B[0m\u001B[1;33m(\u001B[0m\u001B[1;33m*\u001B[0m\u001B[0margs\u001B[0m\u001B[1;33m,\u001B[0m \u001B[1;33m**\u001B[0m\u001B[0mkwargs\u001B[0m\u001B[1;33m)\u001B[0m\u001B[1;33m\u001B[0m\u001B[1;33m\u001B[0m\u001B[0m\n",
              "\u001B[1;31mType:\u001B[0m            _ArrayFunctionDispatcher\n",
              "\u001B[1;31mString form:\u001B[0m     \u003Cfunction append at 0x0000012FF4800C20\u003E\n",
              "\u001B[1;31mFile:\u001B[0m            c:\\programdata\\anaconda3\\lib\\site-packages\\numpy\\lib\\function_base.py\n",
              "\u001B[1;31mDocstring:\u001B[0m      \n",
              "Append values to the end of an array.\n",
              "\n",
              "Parameters\n",
              "----------\n",
              "arr : array_like\n",
              "    Values are appended to a copy of this array.\n",
              "values : array_like\n",
              "    These values are appended to a copy of `arr`.  It must be of the\n",
              "    correct shape (the same shape as `arr`, excluding `axis`).  If\n",
              "    `axis` is not specified, `values` can be any shape and will be\n",
              "    flattened before use.\n",
              "axis : int, optional\n",
              "    The axis along which `values` are appended.  If `axis` is not\n",
              "    given, both `arr` and `values` are flattened before use.\n",
              "\n",
              "Returns\n",
              "-------\n",
              "append : ndarray\n",
              "    A copy of `arr` with `values` appended to `axis`.  Note that\n",
              "    `append` does not occur in-place: a new array is allocated and\n",
              "    filled.  If `axis` is None, `out` is a flattened array.\n",
              "\n",
              "See Also\n",
              "--------\n",
              "insert : Insert elements into an array.\n",
              "delete : Delete elements from an array.\n",
              "\n",
              "Examples\n",
              "--------\n",
              "\u003E\u003E\u003E np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])\n",
              "array([1, 2, 3, ..., 7, 8, 9])\n",
              "\n",
              "When `axis` is specified, `values` must have the correct shape.\n",
              "\n",
              "\u003E\u003E\u003E np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)\n",
              "array([[1, 2, 3],\n",
              "       [4, 5, 6],\n",
              "       [7, 8, 9]])\n",
              "\u003E\u003E\u003E np.append([[1, 2, 3], [4, 5, 6]], [7, 8, 9], axis=0)\n",
              "Traceback (most recent call last):\n",
              "    ...\n",
              "ValueError: all the input arrays must have same number of dimensions, but\n",
              "the array at index 0 has 2 dimension(s) and the array at index 1 has 1\n",
              "dimension(s)\n",
              "\u001B[1;31mClass docstring:\u001B[0m\n",
              "Class to wrap functions with checks for __array_function__ overrides.\n",
              "\n",
              "All arguments are required, and can only be passed by position.\n",
              "\n",
              "Parameters\n",
              "----------\n",
              "dispatcher : function or None\n",
              "    The dispatcher function that returns a single sequence-like object\n",
              "    of all arguments relevant.  It must have the same signature (except\n",
              "    the default values) as the actual implementation.\n",
              "    If ``None``, this is a ``like=`` dispatcher and the\n",
              "    ``_ArrayFunctionDispatcher`` must be called with ``like`` as the\n",
              "    first (additional and positional) argument.\n",
              "implementation : function\n",
              "    Function that implements the operation on NumPy arrays without\n",
              "    overrides.  Arguments passed calling the ``_ArrayFunctionDispatcher``\n",
              "    will be forwarded to this (and the ``dispatcher``) as if using\n",
              "    ``*args, **kwargs``.\n",
              "\n",
              "Attributes\n",
              "----------\n",
              "_implementation : function\n",
              "    The original implementation passed in."
            ]
          },
          "metadata": {

          },
          "output_type": "display_data"
        }
      ],
      "source": [
        "np.append?"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "## Splitting NumPy Arrays\n",
        "\u003Cul\u003E\u003Cli\u003ESplitting is reverse operation of Joining.\u003C/li\u003E\n",
        "    \u003Cli\u003EJoining merges multiple arrays into one and Splitting breaks one array into multiple.\u003C/li\u003E\n",
        "    \u003Cli\u003EWe use \u003Cb\u003Earray_split()\u003C/b\u003E for splitting arrays, we pass it the array we want to split and the number of splits.\u003C/li\u003E\u003C/ul\u003E"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 14,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "[array([1, 2]), array([3]), array([4]), array([5]), array([6])]\n"
          ]
        }
      ],
      "source": [
        "arr = np.array([1, 2, 3, 4, 5, 6])\n",
        "\n",
        "newarr = np.array_split(arr, 5)\n",
        "\n",
        "print(newarr)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 12,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "[3 4]\n"
          ]
        }
      ],
      "source": [
        "# Access splitted arrays\n",
        "\n",
        "arr = np.array([1, 2, 3, 4, 5, 6])\n",
        "\n",
        "newarr = np.array_split(arr, 3)\n",
        "\n",
        "\n",
        "print(newarr[1])"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {

      },
      "source": [
        "## Splitting 2-D Arrays"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 13,
      "metadata": {

      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]]), array([[11, 12]]), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32), array([], shape=(0, 2), dtype=int32)]\n"
          ]
        }
      ],
      "source": [
        "arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])\n",
        "\n",
        "newarr = np.array_split(arr, 38)\n",
        "\n",
        "print(newarr)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {

      },
      "outputs": [],
      "source": []
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3 (ipykernel)",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.12.7"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 4
}